language: php

php:
        - 7.2
service:
        - mysql


before_install:
        - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
        - mysql -u root --password="" < tests/test.sql
before_script:
        - composer install

script: ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/

