language: php

php:
        - 7.2
services:
        - mysql

before_install:
        - mysql -u root --password="" < test/travis.sql
before_script:
        - composer install

script: ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/EmailTest.php

