language: php

php:
        - 7.2
services:
        - mysql

before_install:
        - mysql -u root --password="" < tests/test.sql
        - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
before_script:
        - composer install

script: ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/

